--- Converted from a base theme to the Horizon Candy Milk (Light) palette.
--- All colors match the user's specific requests.
--- Generated by the model.

local palette = {
  ansi = {
    bright = {
      blue = '#059e66',
      cyan = '#da103f',
      green = '#059e66',
      magenta = '#8a31b9',
      red = '#da103f',
      yellow = '#f77d26',
    },
    normal = {
      blue = '#059e66',
      cyan = '#da103f',
      green = '#059e66',
      magenta = '#8a31b9',
      red = '#da103f',
      yellow = '#f77d26',
    },
  },
  syntax = {
    amethyst = '#8a31b9',
    black = '#333333',
    crimson = '#da103f',
    elm = '#059e66',
    jaffa = '#f77d26',
    tango = '#f77d26',
    thunderbird = '#da103f',
  },
  ui = {
    accent = '#f9cbbe',
    accentAlt = '#F9CEC3', -- Mantido original
    background = '#fdf0ed',
    backgroundAlt = '#FADAD1',
    border = '#1A1C23', -- Mantido original
    darkText = '#06060c',
    lightText = '#D5D8DA', -- Mantido original
    modified = '#1EAEAE', -- Mantido original
    negative = '#F43E5C', -- Mantido original
    positive = '#07DA8C', -- Mantido original
    secondaryAccent = '#E73665', -- Mantido original
    secondaryAccentAlt = '#E84A72', -- Mantido original
    shadow = '#16161C', -- Mantido original
    tertiaryAccent = '#f77d26',
    warning = '#1EB980', -- Mantido original
  },
}

local theme = {
  active_line_number_fg = '#827B7D', -- Mantido original
  bg = '#fdf0ed', -- Fundo
  class_variable = {
    fg = '#f77d26', -- Cor forte
  },
  code_block = {
    fg = '#f77d26', -- Cor forte
  },
  codelens_fg = '#FBDFD8', -- Mantido original
  color_column_fg = '#FCE6E0', -- Mantido original
  comment = {
    fg = '#333333', -- Comentário (transparência removida para a configuração Lua)
    italic = true,
  },
  constant = {
    fg = '#f77d26', -- Número / Cor forte
  },
  cursor_bg = '#f77d26', -- Cor forte
  cursor_fg = '#fdf0ed', -- Fundo
  cursorline_bg = '#FCE5DF', -- Mantido original
  delimiter = {
    fg = '#06060c', -- Operador
  },
  diff_added_bg = '#E4EEE3', -- Mantido original
  diff_deleted_bg = '#FCDEDF', -- Mantido original
  error = '#F43E5C', -- Mantido original
  external_link = '#E73665', -- Mantido original
  fg = '#06060c', -- Texto
  field = {
    fg = '#f77d26', -- Cor forte
  },
  float_bg = '#f9cbbe', -- Botão
  float_border = '#f9cbbe', -- Botão
  func = {
    fg = '#da103f', -- Função
  },
  git_added_fg = '#61CAA1', -- Mantido original
  git_deleted_fg = '#F43E5C', -- Mantido original
  git_ignored_fg = '#B3AAA9', -- Mantido original
  git_modified_fg = '#f77d26', -- Cor forte
  git_untracked_fg = '#1EB980', -- Mantido original
  inactive_line_number_fg = '#E4D9D7', -- Mantido original
  indent_guide_active_fg = '#f9cbbe', -- Botão
  indent_guide_fg = '#FBDED6', -- Mantido original
  keyword = {
    fg = '#8a31b9', -- Palavra-chave
  },
  link = {
    fg = '#059e66', -- String
  },
  match_paren = '#FBDFD8', -- Mantido original
  operator = {
    fg = '#06060c', -- Operador
  },
  parameter = {
    italic = true,
  },
  pmenu_bg = '#f9cbbe', -- Botão
  pmenu_item_sel_fg = '#06060c', -- Texto do botão
  pmenu_thumb_bg = '#FBDFD8', -- Mantido original
  pmenu_thumb_fg = '#F9D1C7', -- Mantido original
  regex = {
    fg = '#f77d26', -- Cor forte
  },
  sidebar_bg = '#fdf0ed', -- Fundo
  sidebar_fg = '#06060c', -- Texto
  sign_added_bg = '#51E1A9', -- Mantido original
  sign_deleted_bg = '#F77388', -- Mantido original
  sign_modified_bg = '#61C2C1', -- Mantido original
  special_keyword = {
    fg = '#8a31b9', -- Palavra-chave
  },
  statusline_active_fg = '#f9cbbe', -- Botão
  statusline_bg = '#fdf0ed', -- Fundo
  statusline_fg = '#06060c', -- Texto
  storage = {
    fg = '#8a31b9', -- Palavra-chave
  },
  string = {
    fg = '#059e66', -- String
  },
  structure = {
    fg = '#f77d26', -- Cor forte
  },
  tag = {
    fg = '#da103f', -- Função
    italic = true,
  },
  template_delimiter = {
    fg = '#8a31b9', -- Palavra-chave
  },
  term_cursor_bg = '#06060c', -- Texto
  term_cursor_fg = '#FAD8D0', -- Mantido original
  title = {
    fg = '#f77d26', -- Cor forte
  },
  type = {
    fg = '#f77d26', -- Cor forte
  },
  variable = {
    fg = '#da103f', -- Função
  },
  visual = '#f9cbbe', -- Botão
  warning = '#61CAA1', -- Mantido original
  winbar = '#f9cbbe', -- Botão
  winseparator_fg = '#E6DBD9', -- Mantido original
}

return { theme = theme, palette = palette }
