--- Converted from a base theme to the Horizon Candy (Dark) palette.
--- All colors match the user's specific requests.
--- Generated by the model.

local palette = {
  ansi = {
    bright = {
      blue = '#87cefa',
      cyan = '#7cffcd',
      green = '#7cffcd',
      magenta = '#c6a7ff',
      red = '#EC6A88',
      yellow = '#ffc887',
    },
    normal = {
      blue = '#87cefa',
      cyan = '#7cffcd',
      green = '#7cffcd',
      magenta = '#c6a7ff',
      red = '#E95678',
      yellow = '#ffc887',
    },
  },
  syntax = {
    apricot = '#ffc887',
    cranberry = '#E95678', -- Kept original as no red was provided in the palette
    gray = '#BBBBBB',
    lavender = '#c6a7ff',
    rosebud = '#ffc887',
    tacao = '#ffc887',
    turquoise = '#7cffcd',
  },
  ui = {
    accent = '#2e303e',
    accentAlt = '#6C6F93', -- Kept original
    background = '#1c1e26',
    backgroundAlt = '#232530',
    border = '#1A1C23', -- Kept original
    darkText = '#06060C', -- Kept original
    lightText = '#c9c3d6',
    modified = '#21BFC2', -- Kept original
    negative = '#F43E5C', -- Kept original
    positive = '#09F7A0', -- Kept original
    secondaryAccent = '#E9436D', -- Kept original
    secondaryAccentAlt = '#E95378', -- Kept original
    shadow = '#16161C', -- Kept original
    tertiaryAccent = '#ffc887',
    warning = '#27D797', -- Kept original
  },
}

local theme = {
  active_line_number_fg = '#797B80', -- Kept original
  bg = '#1c1e26', -- Fundo
  class_variable = {
    fg = '#ffc887', -- Cor forte
  },
  code_block = {
    fg = '#ffc887', -- Cor forte
  },
  codelens_fg = '#44475D', -- Kept original
  color_column_fg = '#343647', -- Kept original
  comment = {
    fg = '#a3a0b3', -- Comentário (transparency removed for Lua config)
    italic = true,
  },
  constant = {
    fg = '#ffc887', -- Número/Cor forte
  },
  cursor_bg = '#ffc887', -- Cor forte
  cursor_fg = '#1c1e26', -- Fundo
  cursorline_bg = '#232530', -- Um pouco mais escuro que o fundo para destaque
  delimiter = {
    fg = '#bbbbbb', -- Operador
  },
  diff_added_bg = '#1A3432', -- Kept original
  diff_deleted_bg = '#4A2024', -- Kept original
  error = '#F43E5C', -- Kept original
  external_link = '#E9436D', -- Kept original
  fg = '#c9c3d6', -- Texto
  field = {
    fg = '#c9c3d6', -- Texto
  },
  float_bg = '#2e303e', -- Botão
  float_border = '#2e303e', -- Botão
  func = {
    fg = '#7cffcd', -- Função
  },
  git_added_fg = '#24A075', -- Kept original
  git_deleted_fg = '#F43E5C', -- Kept original
  git_ignored_fg = '#54565C', -- Kept original
  git_modified_fg = '#ffc887', -- Cor forte
  git_untracked_fg = '#27D797', -- Kept original
  inactive_line_number_fg = '#2F3138', -- Kept original
  indent_guide_active_fg = '#2e303e', -- Botão
  indent_guide_fg = '#252732', -- Kept original
  keyword = {
    fg = '#c6a7ff', -- Palavra-chave
  },
  link = {
    fg = '#87cefa', -- String
  },
  match_paren = '#44475D', -- Kept original
  operator = {
    fg = '#bbbbbb', -- Operador
  },
  parameter = {
    italic = true,
  },
  pmenu_bg = '#2e303e', -- Botão
  pmenu_item_sel_fg = '#c9c3d6', -- Texto do botão
  pmenu_thumb_bg = '#242631', -- Kept original
  pmenu_thumb_fg = '#44475D', -- Kept original
  regex = {
    fg = '#ffc887', -- Cor forte
  },
  sidebar_bg = '#1c1e26', -- Fundo
  sidebar_fg = '#c9c3d6', -- Texto
  sign_added_bg = '#0FB67B', -- Kept original
  sign_deleted_bg = '#B3344C', -- Kept original
  sign_modified_bg = '#208F93', -- Kept original
  special_keyword = {
    fg = '#c6a7ff', -- Palavra-chave
  },
  statusline_active_fg = '#2e303e', -- Botão
  statusline_bg = '#1c1e26', -- Fundo
  statusline_fg = '#c9c3d6', -- Texto
  storage = {
    fg = '#c6a7ff', -- Palavra-chave
  },
  string = {
    fg = '#87cefa', -- String
  },
  structure = {
    fg = '#c9c3d6', -- Texto
  },
  tag = {
    fg = '#ffc887', -- Cor forte
    italic = true,
  },
  template_delimiter = {
    fg = '#c6a7ff', -- Palavra-chave
  },
  term_cursor_bg = '#c9c3d6', -- Texto
  term_cursor_fg = '#1c1e26', -- Fundo
  title = {
    fg = '#ffc887', -- Cor forte
  },
  type = {
    fg = '#c9c3d6', -- Texto
  },
  variable = {
    fg = '#ffc887', -- Cor forte
  },
  visual = '#2e303e', -- Botão
  warning = '#24A075', -- Kept original
  winbar = '#2e303e', -- Botão
  winseparator_fg = '#1A1C23', -- Kept original
}

return { theme = theme, palette = palette }
